// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.4
// source: component/geodata/router/config.proto

package router

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Type of domain value.
type Domain_Type int32

const (
	// The value is used as is.
	Domain_Plain Domain_Type = 0
	// The value is used as a regular expression.
	Domain_Regex Domain_Type = 1
	// The value is a root domain.
	Domain_Domain Domain_Type = 2
	// The value is a domain.
	Domain_Full Domain_Type = 3
)

// Enum value maps for Domain_Type.
var (
	Domain_Type_name = map[int32]string{
		0: "Plain",
		1: "Regex",
		2: "Domain",
		3: "Full",
	}
	Domain_Type_value = map[string]int32{
		"Plain":  0,
		"Regex":  1,
		"Domain": 2,
		"Full":   3,
	}
)

func (x Domain_Type) Enum() *Domain_Type {
	p := new(Domain_Type)
	*p = x
	return p
}

func (x Domain_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Domain_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_component_geodata_router_config_proto_enumTypes[0].Descriptor()
}

func (Domain_Type) Type() protoreflect.EnumType {
	return &file_component_geodata_router_config_proto_enumTypes[0]
}

func (x Domain_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Domain for routing decision.
type Domain struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Type      Domain_Type            `protobuf:"varint,1,opt,name=type,proto3,enum=quirktiva.component.geodata.router.Domain_Type"`
	xxx_hidden_Value     string                 `protobuf:"bytes,2,opt,name=value,proto3"`
	xxx_hidden_Attribute *[]*Domain_Attribute   `protobuf:"bytes,3,rep,name=attribute,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Domain) Reset() {
	*x = Domain{}
	mi := &file_component_geodata_router_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Domain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Domain) ProtoMessage() {}

func (x *Domain) ProtoReflect() protoreflect.Message {
	mi := &file_component_geodata_router_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Domain) GetType() Domain_Type {
	if x != nil {
		return x.xxx_hidden_Type
	}
	return Domain_Plain
}

func (x *Domain) GetValue() string {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return ""
}

func (x *Domain) GetAttribute() []*Domain_Attribute {
	if x != nil {
		if x.xxx_hidden_Attribute != nil {
			return *x.xxx_hidden_Attribute
		}
	}
	return nil
}

func (x *Domain) SetType(v Domain_Type) {
	x.xxx_hidden_Type = v
}

func (x *Domain) SetValue(v string) {
	x.xxx_hidden_Value = v
}

func (x *Domain) SetAttribute(v []*Domain_Attribute) {
	x.xxx_hidden_Attribute = &v
}

type Domain_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Domain matching type.
	Type Domain_Type
	// Domain value.
	Value string
	// Attributes of this domain. May be used for filtering.
	Attribute []*Domain_Attribute
}

func (b0 Domain_builder) Build() *Domain {
	m0 := &Domain{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Type = b.Type
	x.xxx_hidden_Value = b.Value
	x.xxx_hidden_Attribute = &b.Attribute
	return m0
}

// IP for routing decision, in CIDR form.
type CIDR struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ip     []byte                 `protobuf:"bytes,1,opt,name=ip,proto3"`
	xxx_hidden_Prefix uint32                 `protobuf:"varint,2,opt,name=prefix,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CIDR) Reset() {
	*x = CIDR{}
	mi := &file_component_geodata_router_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CIDR) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CIDR) ProtoMessage() {}

func (x *CIDR) ProtoReflect() protoreflect.Message {
	mi := &file_component_geodata_router_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CIDR) GetIp() []byte {
	if x != nil {
		return x.xxx_hidden_Ip
	}
	return nil
}

func (x *CIDR) GetPrefix() uint32 {
	if x != nil {
		return x.xxx_hidden_Prefix
	}
	return 0
}

func (x *CIDR) SetIp(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Ip = v
}

func (x *CIDR) SetPrefix(v uint32) {
	x.xxx_hidden_Prefix = v
}

type CIDR_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// IP address, should be either 4 or 16 bytes.
	Ip []byte
	// Number of leading ones in the network mask.
	Prefix uint32
}

func (b0 CIDR_builder) Build() *CIDR {
	m0 := &CIDR{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ip = b.Ip
	x.xxx_hidden_Prefix = b.Prefix
	return m0
}

type GeoIP struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_CountryCode  string                 `protobuf:"bytes,1,opt,name=country_code,json=countryCode,proto3"`
	xxx_hidden_Cidr         *[]*CIDR               `protobuf:"bytes,2,rep,name=cidr,proto3"`
	xxx_hidden_ReverseMatch bool                   `protobuf:"varint,3,opt,name=reverse_match,json=reverseMatch,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *GeoIP) Reset() {
	*x = GeoIP{}
	mi := &file_component_geodata_router_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoIP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoIP) ProtoMessage() {}

func (x *GeoIP) ProtoReflect() protoreflect.Message {
	mi := &file_component_geodata_router_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GeoIP) GetCountryCode() string {
	if x != nil {
		return x.xxx_hidden_CountryCode
	}
	return ""
}

func (x *GeoIP) GetCidr() []*CIDR {
	if x != nil {
		if x.xxx_hidden_Cidr != nil {
			return *x.xxx_hidden_Cidr
		}
	}
	return nil
}

func (x *GeoIP) GetReverseMatch() bool {
	if x != nil {
		return x.xxx_hidden_ReverseMatch
	}
	return false
}

func (x *GeoIP) SetCountryCode(v string) {
	x.xxx_hidden_CountryCode = v
}

func (x *GeoIP) SetCidr(v []*CIDR) {
	x.xxx_hidden_Cidr = &v
}

func (x *GeoIP) SetReverseMatch(v bool) {
	x.xxx_hidden_ReverseMatch = v
}

type GeoIP_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	CountryCode  string
	Cidr         []*CIDR
	ReverseMatch bool
}

func (b0 GeoIP_builder) Build() *GeoIP {
	m0 := &GeoIP{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_CountryCode = b.CountryCode
	x.xxx_hidden_Cidr = &b.Cidr
	x.xxx_hidden_ReverseMatch = b.ReverseMatch
	return m0
}

type GeoIPList struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Entry *[]*GeoIP              `protobuf:"bytes,1,rep,name=entry,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GeoIPList) Reset() {
	*x = GeoIPList{}
	mi := &file_component_geodata_router_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoIPList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoIPList) ProtoMessage() {}

func (x *GeoIPList) ProtoReflect() protoreflect.Message {
	mi := &file_component_geodata_router_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GeoIPList) GetEntry() []*GeoIP {
	if x != nil {
		if x.xxx_hidden_Entry != nil {
			return *x.xxx_hidden_Entry
		}
	}
	return nil
}

func (x *GeoIPList) SetEntry(v []*GeoIP) {
	x.xxx_hidden_Entry = &v
}

type GeoIPList_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Entry []*GeoIP
}

func (b0 GeoIPList_builder) Build() *GeoIPList {
	m0 := &GeoIPList{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Entry = &b.Entry
	return m0
}

type GeoSite struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_CountryCode string                 `protobuf:"bytes,1,opt,name=country_code,json=countryCode,proto3"`
	xxx_hidden_Domain      *[]*Domain             `protobuf:"bytes,2,rep,name=domain,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GeoSite) Reset() {
	*x = GeoSite{}
	mi := &file_component_geodata_router_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoSite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoSite) ProtoMessage() {}

func (x *GeoSite) ProtoReflect() protoreflect.Message {
	mi := &file_component_geodata_router_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GeoSite) GetCountryCode() string {
	if x != nil {
		return x.xxx_hidden_CountryCode
	}
	return ""
}

func (x *GeoSite) GetDomain() []*Domain {
	if x != nil {
		if x.xxx_hidden_Domain != nil {
			return *x.xxx_hidden_Domain
		}
	}
	return nil
}

func (x *GeoSite) SetCountryCode(v string) {
	x.xxx_hidden_CountryCode = v
}

func (x *GeoSite) SetDomain(v []*Domain) {
	x.xxx_hidden_Domain = &v
}

type GeoSite_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	CountryCode string
	Domain      []*Domain
}

func (b0 GeoSite_builder) Build() *GeoSite {
	m0 := &GeoSite{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_CountryCode = b.CountryCode
	x.xxx_hidden_Domain = &b.Domain
	return m0
}

type GeoSiteList struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Entry *[]*GeoSite            `protobuf:"bytes,1,rep,name=entry,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GeoSiteList) Reset() {
	*x = GeoSiteList{}
	mi := &file_component_geodata_router_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoSiteList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoSiteList) ProtoMessage() {}

func (x *GeoSiteList) ProtoReflect() protoreflect.Message {
	mi := &file_component_geodata_router_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GeoSiteList) GetEntry() []*GeoSite {
	if x != nil {
		if x.xxx_hidden_Entry != nil {
			return *x.xxx_hidden_Entry
		}
	}
	return nil
}

func (x *GeoSiteList) SetEntry(v []*GeoSite) {
	x.xxx_hidden_Entry = &v
}

type GeoSiteList_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Entry []*GeoSite
}

func (b0 GeoSiteList_builder) Build() *GeoSiteList {
	m0 := &GeoSiteList{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Entry = &b.Entry
	return m0
}

type Domain_Attribute struct {
	state                 protoimpl.MessageState        `protogen:"opaque.v1"`
	xxx_hidden_Key        string                        `protobuf:"bytes,1,opt,name=key,proto3"`
	xxx_hidden_TypedValue isDomain_Attribute_TypedValue `protobuf_oneof:"typed_value"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Domain_Attribute) Reset() {
	*x = Domain_Attribute{}
	mi := &file_component_geodata_router_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Domain_Attribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Domain_Attribute) ProtoMessage() {}

func (x *Domain_Attribute) ProtoReflect() protoreflect.Message {
	mi := &file_component_geodata_router_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Domain_Attribute) GetKey() string {
	if x != nil {
		return x.xxx_hidden_Key
	}
	return ""
}

func (x *Domain_Attribute) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.xxx_hidden_TypedValue.(*domain_Attribute_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *Domain_Attribute) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.xxx_hidden_TypedValue.(*domain_Attribute_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *Domain_Attribute) SetKey(v string) {
	x.xxx_hidden_Key = v
}

func (x *Domain_Attribute) SetBoolValue(v bool) {
	x.xxx_hidden_TypedValue = &domain_Attribute_BoolValue{v}
}

func (x *Domain_Attribute) SetIntValue(v int64) {
	x.xxx_hidden_TypedValue = &domain_Attribute_IntValue{v}
}

func (x *Domain_Attribute) HasTypedValue() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_TypedValue != nil
}

func (x *Domain_Attribute) HasBoolValue() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_TypedValue.(*domain_Attribute_BoolValue)
	return ok
}

func (x *Domain_Attribute) HasIntValue() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_TypedValue.(*domain_Attribute_IntValue)
	return ok
}

func (x *Domain_Attribute) ClearTypedValue() {
	x.xxx_hidden_TypedValue = nil
}

func (x *Domain_Attribute) ClearBoolValue() {
	if _, ok := x.xxx_hidden_TypedValue.(*domain_Attribute_BoolValue); ok {
		x.xxx_hidden_TypedValue = nil
	}
}

func (x *Domain_Attribute) ClearIntValue() {
	if _, ok := x.xxx_hidden_TypedValue.(*domain_Attribute_IntValue); ok {
		x.xxx_hidden_TypedValue = nil
	}
}

const Domain_Attribute_TypedValue_not_set_case case_Domain_Attribute_TypedValue = 0
const Domain_Attribute_BoolValue_case case_Domain_Attribute_TypedValue = 2
const Domain_Attribute_IntValue_case case_Domain_Attribute_TypedValue = 3

func (x *Domain_Attribute) WhichTypedValue() case_Domain_Attribute_TypedValue {
	if x == nil {
		return Domain_Attribute_TypedValue_not_set_case
	}
	switch x.xxx_hidden_TypedValue.(type) {
	case *domain_Attribute_BoolValue:
		return Domain_Attribute_BoolValue_case
	case *domain_Attribute_IntValue:
		return Domain_Attribute_IntValue_case
	default:
		return Domain_Attribute_TypedValue_not_set_case
	}
}

type Domain_Attribute_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Key string
	// Fields of oneof xxx_hidden_TypedValue:
	BoolValue *bool
	IntValue  *int64
	// -- end of xxx_hidden_TypedValue
}

func (b0 Domain_Attribute_builder) Build() *Domain_Attribute {
	m0 := &Domain_Attribute{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Key = b.Key
	if b.BoolValue != nil {
		x.xxx_hidden_TypedValue = &domain_Attribute_BoolValue{*b.BoolValue}
	}
	if b.IntValue != nil {
		x.xxx_hidden_TypedValue = &domain_Attribute_IntValue{*b.IntValue}
	}
	return m0
}

type case_Domain_Attribute_TypedValue protoreflect.FieldNumber

func (x case_Domain_Attribute_TypedValue) String() string {
	md := file_component_geodata_router_config_proto_msgTypes[6].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isDomain_Attribute_TypedValue interface {
	isDomain_Attribute_TypedValue()
}

type domain_Attribute_BoolValue struct {
	BoolValue bool `protobuf:"varint,2,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type domain_Attribute_IntValue struct {
	IntValue int64 `protobuf:"varint,3,opt,name=int_value,json=intValue,proto3,oneof"`
}

func (*domain_Attribute_BoolValue) isDomain_Attribute_TypedValue() {}

func (*domain_Attribute_IntValue) isDomain_Attribute_TypedValue() {}

var File_component_geodata_router_config_proto protoreflect.FileDescriptor

const file_component_geodata_router_config_proto_rawDesc = "" +
	"\n" +
	"%component/geodata/router/config.proto\x12\"quirktiva.component.geodata.router\"\xd9\x02\n" +
	"\x06Domain\x12C\n" +
	"\x04type\x18\x01 \x01(\x0e2/.quirktiva.component.geodata.router.Domain.TypeR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12R\n" +
	"\tattribute\x18\x03 \x03(\v24.quirktiva.component.geodata.router.Domain.AttributeR\tattribute\x1al\n" +
	"\tAttribute\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x02 \x01(\bH\x00R\tboolValue\x12\x1d\n" +
	"\tint_value\x18\x03 \x01(\x03H\x00R\bintValueB\r\n" +
	"\vtyped_value\"2\n" +
	"\x04Type\x12\t\n" +
	"\x05Plain\x10\x00\x12\t\n" +
	"\x05Regex\x10\x01\x12\n" +
	"\n" +
	"\x06Domain\x10\x02\x12\b\n" +
	"\x04Full\x10\x03\".\n" +
	"\x04CIDR\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\fR\x02ip\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\rR\x06prefix\"\x8d\x01\n" +
	"\x05GeoIP\x12!\n" +
	"\fcountry_code\x18\x01 \x01(\tR\vcountryCode\x12<\n" +
	"\x04cidr\x18\x02 \x03(\v2(.quirktiva.component.geodata.router.CIDRR\x04cidr\x12#\n" +
	"\rreverse_match\x18\x03 \x01(\bR\freverseMatch\"L\n" +
	"\tGeoIPList\x12?\n" +
	"\x05entry\x18\x01 \x03(\v2).quirktiva.component.geodata.router.GeoIPR\x05entry\"p\n" +
	"\aGeoSite\x12!\n" +
	"\fcountry_code\x18\x01 \x01(\tR\vcountryCode\x12B\n" +
	"\x06domain\x18\x02 \x03(\v2*.quirktiva.component.geodata.router.DomainR\x06domain\"P\n" +
	"\vGeoSiteList\x12A\n" +
	"\x05entry\x18\x01 \x03(\v2+.quirktiva.component.geodata.router.GeoSiteR\x05entryB\x88\x01\n" +
	"&com.quirktiva.component.geodata.routerP\x01Z7github.com/yaling888/quirktiva/component/geodata/router\xaa\x02\"Quirktiva.Component.Geodata.Routerb\x06proto3"

var file_component_geodata_router_config_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_component_geodata_router_config_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_component_geodata_router_config_proto_goTypes = []any{
	(Domain_Type)(0),         // 0: quirktiva.component.geodata.router.Domain.Type
	(*Domain)(nil),           // 1: quirktiva.component.geodata.router.Domain
	(*CIDR)(nil),             // 2: quirktiva.component.geodata.router.CIDR
	(*GeoIP)(nil),            // 3: quirktiva.component.geodata.router.GeoIP
	(*GeoIPList)(nil),        // 4: quirktiva.component.geodata.router.GeoIPList
	(*GeoSite)(nil),          // 5: quirktiva.component.geodata.router.GeoSite
	(*GeoSiteList)(nil),      // 6: quirktiva.component.geodata.router.GeoSiteList
	(*Domain_Attribute)(nil), // 7: quirktiva.component.geodata.router.Domain.Attribute
}
var file_component_geodata_router_config_proto_depIdxs = []int32{
	0, // 0: quirktiva.component.geodata.router.Domain.type:type_name -> quirktiva.component.geodata.router.Domain.Type
	7, // 1: quirktiva.component.geodata.router.Domain.attribute:type_name -> quirktiva.component.geodata.router.Domain.Attribute
	2, // 2: quirktiva.component.geodata.router.GeoIP.cidr:type_name -> quirktiva.component.geodata.router.CIDR
	3, // 3: quirktiva.component.geodata.router.GeoIPList.entry:type_name -> quirktiva.component.geodata.router.GeoIP
	1, // 4: quirktiva.component.geodata.router.GeoSite.domain:type_name -> quirktiva.component.geodata.router.Domain
	5, // 5: quirktiva.component.geodata.router.GeoSiteList.entry:type_name -> quirktiva.component.geodata.router.GeoSite
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_component_geodata_router_config_proto_init() }
func file_component_geodata_router_config_proto_init() {
	if File_component_geodata_router_config_proto != nil {
		return
	}
	file_component_geodata_router_config_proto_msgTypes[6].OneofWrappers = []any{
		(*domain_Attribute_BoolValue)(nil),
		(*domain_Attribute_IntValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_component_geodata_router_config_proto_rawDesc), len(file_component_geodata_router_config_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_component_geodata_router_config_proto_goTypes,
		DependencyIndexes: file_component_geodata_router_config_proto_depIdxs,
		EnumInfos:         file_component_geodata_router_config_proto_enumTypes,
		MessageInfos:      file_component_geodata_router_config_proto_msgTypes,
	}.Build()
	File_component_geodata_router_config_proto = out.File
	file_component_geodata_router_config_proto_goTypes = nil
	file_component_geodata_router_config_proto_depIdxs = nil
}
