// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && linux

package tc

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type bpfParams struct {
	ClashMark     uint32
	TunIfindex    uint32
	FakeIp4Prefix uint32
	FakeIp6Prefix [2]uint32
}

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
	bpfVariableSpecs
}

// bpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	TcTun55Func *ebpf.ProgramSpec `ebpf:"tc_tun_5_5_func"`
	TcTunFunc   *ebpf.ProgramSpec `ebpf:"tc_tun_func"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	ParamsMap *ebpf.MapSpec `ebpf:"params_map"`
}

// bpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfVariableSpecs struct {
	ClashMark     *ebpf.VariableSpec `ebpf:"clash_mark"`
	FakeIp4Prefix *ebpf.VariableSpec `ebpf:"fake_ip4_prefix"`
	FakeIp6Prefix *ebpf.VariableSpec `ebpf:"fake_ip6_prefix"`
	TunIfindex    *ebpf.VariableSpec `ebpf:"tun_ifindex"`
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
	bpfVariables
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	ParamsMap *ebpf.Map `ebpf:"params_map"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.ParamsMap,
	)
}

// bpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfVariables struct {
	ClashMark     *ebpf.Variable `ebpf:"clash_mark"`
	FakeIp4Prefix *ebpf.Variable `ebpf:"fake_ip4_prefix"`
	FakeIp6Prefix *ebpf.Variable `ebpf:"fake_ip6_prefix"`
	TunIfindex    *ebpf.Variable `ebpf:"tun_ifindex"`
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	TcTun55Func *ebpf.Program `ebpf:"tc_tun_5_5_func"`
	TcTunFunc   *ebpf.Program `ebpf:"tc_tun_func"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.TcTun55Func,
		p.TcTunFunc,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfeb.o
var _BpfBytes []byte
