// Code generated by bpf2go; DO NOT EDIT.
//go:build linux

package tc

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadTun_redir_to_host returns the embedded CollectionSpec for tun_redir_to_host.
func loadTun_redir_to_host() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Tun_redir_to_hostBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tun_redir_to_host: %w", err)
	}

	return spec, err
}

// loadTun_redir_to_hostObjects loads tun_redir_to_host and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tun_redir_to_hostObjects
//	*tun_redir_to_hostPrograms
//	*tun_redir_to_hostMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTun_redir_to_hostObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTun_redir_to_host()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tun_redir_to_hostSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tun_redir_to_hostSpecs struct {
	tun_redir_to_hostProgramSpecs
	tun_redir_to_hostMapSpecs
	tun_redir_to_hostVariableSpecs
}

// tun_redir_to_hostProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tun_redir_to_hostProgramSpecs struct {
	TcTunRedirectToHost *ebpf.ProgramSpec `ebpf:"tc_tun_redirect_to_host"`
}

// tun_redir_to_hostMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tun_redir_to_hostMapSpecs struct {
	HostsMap *ebpf.MapSpec `ebpf:"hosts_map"`
}

// tun_redir_to_hostVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tun_redir_to_hostVariableSpecs struct {
}

// tun_redir_to_hostObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTun_redir_to_hostObjects or ebpf.CollectionSpec.LoadAndAssign.
type tun_redir_to_hostObjects struct {
	tun_redir_to_hostPrograms
	tun_redir_to_hostMaps
	tun_redir_to_hostVariables
}

func (o *tun_redir_to_hostObjects) Close() error {
	return _Tun_redir_to_hostClose(
		&o.tun_redir_to_hostPrograms,
		&o.tun_redir_to_hostMaps,
	)
}

// tun_redir_to_hostMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTun_redir_to_hostObjects or ebpf.CollectionSpec.LoadAndAssign.
type tun_redir_to_hostMaps struct {
	HostsMap *ebpf.Map `ebpf:"hosts_map"`
}

func (m *tun_redir_to_hostMaps) Close() error {
	return _Tun_redir_to_hostClose(
		m.HostsMap,
	)
}

// tun_redir_to_hostVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTun_redir_to_hostObjects or ebpf.CollectionSpec.LoadAndAssign.
type tun_redir_to_hostVariables struct {
}

// tun_redir_to_hostPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTun_redir_to_hostObjects or ebpf.CollectionSpec.LoadAndAssign.
type tun_redir_to_hostPrograms struct {
	TcTunRedirectToHost *ebpf.Program `ebpf:"tc_tun_redirect_to_host"`
}

func (p *tun_redir_to_hostPrograms) Close() error {
	return _Tun_redir_to_hostClose(
		p.TcTunRedirectToHost,
	)
}

func _Tun_redir_to_hostClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tun_redir_to_host_bpf.o
var _Tun_redir_to_hostBytes []byte
